import { useState, useEffect, useRef } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import axios from 'axios'
import jsPDF from 'jspdf'
import html2canvas from 'html2canvas'
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts'
const API = 'http://localhost:5000/api/students'

function StudentDetail({ darkMode }) {
  const { id } = useParams()
  const navigate = useNavigate()
  const [student, setStudent] = useState(null)
  const [editing, setEditing] = useState(false)
  const [editSubjects, setEditSubjects] = useState([])
  useEffect(() => {
    fetchStudent()
  }, [])

  const fetchStudent = async () => {
    const res = await axios.get(`${API}/${id}`)
    setStudent(res.data)
  }
  const handleEdit = () => {
    setEditSubjects(student.subjects.map(s => ({...s})))
    setEditing(true)
  }

  const handleEditChange = (index, field, value) => {
    const updated = [...editSubjects]
    updated[index][field] = value
    setEditSubjects(updated)
  }

  const handleSave = async () => {
    await axios.put(`${API}/${id}`, { subjects: editSubjects })
    setEditing(false)
    fetchStudent()
  }

  const getGrade = (marks, total) => {
    const percentage = (marks / total) * 100
    if (percentage >= 90) return 'A+'
    if (percentage >= 80) return 'A'
    if (percentage >= 70) return 'B'
    if (percentage >= 60) return 'C'
    if (percentage >= 50) return 'D'
    return 'F'
  }
  const getGPA = (subjects) => {
    if (!subjects.length) return 0
    const gradePoints = subjects.map(sub => {
      const percentage = (sub.marks / sub.totalMarks) * 100
      if (percentage >= 90) return 10
      if (percentage >= 80) return 9
      if (percentage >= 70) return 8
      if (percentage >= 60) return 7
      if (percentage >= 50) return 6
      return 0
    })
    const total = gradePoints.reduce((a, b) => a + b, 0)
    return (total / subjects.length).toFixed(2)
  }

  const getPercentage = (subjects) => {
    if (!subjects.length) return 0
    const total = subjects.reduce((a, b) => a + Number(b.totalMarks), 0)
    const marks = subjects.reduce((a, b) => a + Number(b.marks), 0)
    return ((marks / total) * 100).toFixed(2)
  }

  const handlePrint = () => {
    window.print()
  }
  const reportRef = useRef(null)

  const handleExportPDF = () => {
    const printWindow = window.open('', '_blank')
    printWindow.document.write(`
      <html>
        <head>
          <title>${student.name} Report Card</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 20px; }
            h1 { color: #2563eb; text-align: center; }
            h2 { text-align: center; }
            table { width: 100%; border-collapse: collapse; margin-top: 20px; }
            th { background: #2563eb; color: white; padding: 8px; }
            td { padding: 8px; border: 1px solid #ddd; text-align: center; }
            .info { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; margin: 20px 0; }
            .result { text-align: center; padding: 15px; margin-top: 20px; border-radius: 8px; }
            .passed { background: #dcfce7; color: #16a34a; }
            .failed { background: #fee2e2; color: #dc2626; }
            .footer { text-align: center; margin-top: 20px; color: #9ca3af; font-size: 12px; }
          </style>
        </head>
        <body>
          <h1>🎓 Grade Tracker</h1>
          <h2>Student Report Card</h2>
          <div class="info">
            <div><strong>Name:</strong> ${student.name}</div>
            <div><strong>Roll No:</strong> ${student.rollNumber}</div>
            ${student.class ? `<div><strong>Class:</strong> ${student.class}</div>` : ''}
            ${student.section ? `<div><strong>Section:</strong> ${student.section}</div>` : ''}
          </div>
          <table>
            <thead>
              <tr>
                <th>Subject</th>
                <th>Marks</th>
                <th>Total</th>
                <th>Percentage</th>
                <th>Grade</th>
              </tr>
            </thead>
            <tbody>
              ${student.subjects.map(sub => `
                <tr>
                  <td>${sub.name}</td>
                  <td>${sub.marks}</td>
                  <td>${sub.totalMarks}</td>
                  <td>${((sub.marks / sub.totalMarks) * 100).toFixed(1)}%</td>
                  <td><strong>${getGrade(sub.marks, sub.totalMarks)}</strong></td>
                </tr>
              `).join('')}
            </tbody>
          </table>
          <div class="result ${getPercentage(student.subjects) >= 50 ? 'passed' : 'failed'}">
            <h2>${getPercentage(student.subjects)}%</h2>
            <h3>${getPercentage(student.subjects) >= 50 ? '✅ PASSED' : '❌ FAILED'}</h3>
          </div>
          <div class="footer">Generated by Grade Tracker • ${new Date().toLocaleDateString()}</div>
          <script>
            window.onload = function() {
              window.print()
              window.onafterprint = function() {
                window.close()
              }
            }
          </script>
        </body>
      </html>
    `)
    printWindow.document.close()
  }
      

  if (!student) return <p className="text-center mt-10">Loading...</p>

  return (
    <div className={`max-w-2xl mx-auto p-6 ${darkMode ? 'text-white' : 'text-gray-800'}`}>

      {/* Back & Print buttons - hidden when printing */}
      <div className="flex justify-between mb-4 print:hidden gap-2">
        <button onClick={() => navigate('/')}
          className="text-blue-500 hover:underline">
          ← Back to Home
        </button>
        <div className="flex gap-2">
          <button onClick={() => navigate(`/assignments/${id}`)}
            className="bg-purple-500 text-white px-4 py-2 rounded hover:bg-purple-600">
            📝 Assignments
          </button>
          <button onClick={handleEdit}
            className="bg-yellow-500 text-white px-4 py-2 rounded hover:bg-yellow-600">
            ✏️ Edit Marks
          </button>
          <button onClick={handlePrint}
            className="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600">
            🖨️ Print
          </button>
          <button onClick={handleExportPDF}
            className="bg-red-500 text-white px-4 py-2 rounded hover:bg-red-600">
            📄 Export PDF
          </button>
        </div>
        </div>

      {/* Report Card */}
      <div ref={reportRef} className={`rounded-xl shadow p-6 ${darkMode ? 'bg-gray-800' : 'bg-white'}`}>

        {/* Header */}
        <div className="text-center mb-6 border-b pb-4">
          <h1 className="text-2xl font-bold text-blue-600">🎓 Grade Tracker</h1>
          <h2 className="text-xl font-semibold mt-1">Student Report Card</h2>
        </div>

        {/* Student Info */}
        <div className="grid grid-cols-2 gap-4 mb-6">
          <div>
            <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-500'}`}>Student Name</p>
            <p className="font-bold text-lg">{student.name}</p>
          </div>
          <div>
            <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-500'}`}>Roll Number</p>
            <p className="font-bold text-lg">{student.rollNumber}</p>
          </div>
          {student.class && (
            <div>
              <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-500'}`}>Class</p>
              <p className="font-bold">{student.class}</p>
            </div>
          )}
          {student.section && (
            <div>
              <p className={`text-sm ${darkMode ? 'text-gray-400' : 'text-gray-500'}`}>Section</p>
              <p className="font-bold">{student.section}</p>
            </div>
          )}
        </div>

        {/* Subjects Table */}
        <h3 className="font-semibold mb-3">Subject Wise Report</h3>
        {editing ? (
          <div>
            {editSubjects.map((sub, i) => (
              <div key={i} className="flex gap-2 mb-2 items-center">
                <span className="flex-1 font-semibold">{sub.name}</span>
                <input
                  className={`border rounded p-2 w-24 ${darkMode ? 'bg-gray-700 text-white border-gray-600' : ''}`}
                  placeholder="Marks"
                  value={sub.marks}
                  onChange={e => handleEditChange(i, 'marks', e.target.value)}
                />
                <span>/</span>
                <input
                  className={`border rounded p-2 w-24 ${darkMode ? 'bg-gray-700 text-white border-gray-600' : ''}`}
                  placeholder="Total"
                  value={sub.totalMarks}
                  onChange={e => handleEditChange(i, 'totalMarks', e.target.value)}
                />
              </div>
            ))}
            <div className="flex gap-2 mt-3">
              <button onClick={handleSave}
                className="bg-green-500 text-white px-4 py-2 rounded hover:bg-green-600">
                💾 Save Changes
              </button>
              <button onClick={() => setEditing(false)}
                className="bg-gray-500 text-white px-4 py-2 rounded hover:bg-gray-600">
                Cancel
              </button>
            </div>
          </div>
        ) : (
          <table className="w-full text-sm mb-6">
            <thead>
              <tr className="bg-blue-500 text-white">
                <th className="p-2 text-left">Subject</th>
                <th className="p-2">Marks</th>
                <th className="p-2">Total</th>
                <th className="p-2">Percentage</th>
                <th className="p-2">Grade</th>
              </tr>
            </thead>
            <tbody>
              {student.subjects.map((sub, i) => (
                <tr key={i} className={`border-t ${i % 2 === 0 ? darkMode ? 'bg-gray-700' : 'bg-gray-50' : ''}`}>
                  <td className="p-2">{sub.name}</td>
                  <td className="p-2 text-center">{sub.marks}</td>
                  <td className="p-2 text-center">{sub.totalMarks}</td>
                  <td className="p-2 text-center">
                    {((sub.marks / sub.totalMarks) * 100).toFixed(1)}%
                  </td>
                  <td className="p-2 text-center font-bold text-blue-600">
                    {getGrade(sub.marks, sub.totalMarks)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
        {/* Bar Chart */}
        <div className="mb-6">
        <h3 className="font-semibold mb-3">📊 Subject Performance Chart</h3>
        <ResponsiveContainer width="100%" height={250}>
            <BarChart data={student.subjects.map(sub => ({
            name: sub.name,
            marks: Number(sub.marks),
            total: Number(sub.totalMarks),
            percentage: Number(((sub.marks / sub.totalMarks) * 100).toFixed(1))
            }))}>
            <CartesianGrid strokeDasharray="3 3" />
            <XAxis dataKey="name" />
            <YAxis />
            <Tooltip />
            <Bar dataKey="marks" fill="#3b82f6" name="Marks" />
            <Bar dataKey="total" fill="#e5e7eb" name="Total" />
            </BarChart>
        </ResponsiveContainer>
        </div>
        {/* Result Summary */}
<div className={`rounded-lg p-4 text-center ${getPercentage(student.subjects) >= 50 ? 'bg-green-100' : 'bg-red-100'}`}>
  <div className="grid grid-cols-3 gap-4">
    <div>
      <p className="text-3xl font-bold text-blue-600">
        {getPercentage(student.subjects)}%
      </p>
      <p className="text-sm text-gray-500">Percentage</p>
    </div>
    <div>
      <p className="text-3xl font-bold text-purple-600">
        {getGPA(student.subjects)}
      </p>
      <p className="text-sm text-gray-500">GPA (10)</p>
    </div>
    <div>
      <p className={`text-3xl font-bold ${getPercentage(student.subjects) >= 50 ? 'text-green-600' : 'text-red-600'}`}>
        {getPercentage(student.subjects) >= 50 ? '✅' : '❌'}
      </p>
      <p className={`text-sm font-bold ${getPercentage(student.subjects) >= 50 ? 'text-green-600' : 'text-red-600'}`}>
        {getPercentage(student.subjects) >= 50 ? 'PASSED' : 'FAILED'}
      </p>
    </div>
  </div>
</div>

        {/* Footer */}
        <div className="text-center mt-6 text-sm text-gray-400 border-t pt-4">
          <p>Generated by Grade Tracker • {new Date().toLocaleDateString()}</p>
        </div>
      </div>
    </div>
  )
}

export default StudentDetail